{
 "title": "expected_prices_in_30days",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "exec time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT datetime(timestamp/1000, 'unixepoch') as exec_time from metrics ORDER BY timestamp limit 1;",
     "rawQueryText": "SELECT datetime(timestamp/1000, 'unixepoch') as exec_time from metrics ORDER BY timestamp limit 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "experiments",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 0 },
   "targets": [
    {
     "queryText": "select * from experiments;\n",
     "rawQueryText": "select * from experiments;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "expected_prices_in_30days_by_method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT key as expected_price_by_model, value \nFROM metrics\nwhere key like 'expected%';\n\n",
     "rawQueryText": "SELECT key as expected_price_by_model, value \nFROM metrics\nwhere key like 'expected%';\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Indicators",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT key, value \nFROM metrics\n",
     "rawQueryText": "SELECT key, value \nFROM metrics\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}